server:
  port: 9020

spring:
  datasource:
    url: jdbc:mysql://192.168.0.4:3306/reciptRecipe?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: reciptuser
    password: recipereceipt
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    generate-ddl: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  r2dbc:
    url: r2dbc:mysql://192.168.0.4:3306/reciptMember?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: reciptuser
    password: recipereceipt

logging:
  level:
    org.springframework: TRACE