server:
  port: 9020

spring:
  datasource:
    url: jdbc:mysql://192.168.0.4:3306/testdb?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: testuser
    password: test1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  r2dbc:
    url: r2dbc:mysql://192.168.0.4:3306/testdb?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: testuser
    password: test1234

logging:
  level:
    org.springframework: TRACE